create extension if not exists pgcrypto;

create table if not exists public.password_reset_otps (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  email text not null,
  otp_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0 check (attempts >= 0),
  verified boolean not null default false,
  verified_at timestamptz,
  locked_at timestamptz,
  consumed_at timestamptz,
  reset_token_hash text,
  reset_token_expires_at timestamptz,
  request_ip text,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_otps_email_created_idx
  on public.password_reset_otps (email, created_at desc);
create index if not exists password_reset_otps_user_idx
  on public.password_reset_otps (user_id, created_at desc);
create index if not exists password_reset_otps_cleanup_idx
  on public.password_reset_otps (expires_at)
  where consumed_at is null;

create table if not exists public.password_reset_audit_logs (
  id bigint generated by default as identity primary key,
  user_id text,
  email_digest text not null,
  event text not null,
  request_ip text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_audit_user_idx
  on public.password_reset_audit_logs (user_id, created_at desc);
create index if not exists password_reset_audit_event_idx
  on public.password_reset_audit_logs (event, created_at desc);

alter table public.password_reset_otps enable row level security;
alter table public.password_reset_audit_logs enable row level security;

create or replace function public.record_password_reset_otp_failure(
  p_otp_id uuid,
  p_max_attempts integer default 5
)
returns table(attempts integer, locked boolean)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.password_reset_otps
  set
    attempts = password_reset_otps.attempts + 1,
    locked_at = case
      when password_reset_otps.attempts + 1 >= greatest(1, p_max_attempts) then now()
      else password_reset_otps.locked_at
    end
  where id = p_otp_id
    and consumed_at is null
    and verified = false
    and expires_at > now()
    and locked_at is null
  returning
    password_reset_otps.attempts,
    password_reset_otps.locked_at is not null;
end;
$$;

create or replace function public.complete_password_reset(
  p_otp_id uuid,
  p_user_id text,
  p_password_hash text,
  p_token_hash text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_otp_id uuid;
  v_updated integer;
begin
  select id into v_otp_id
  from public.password_reset_otps
  where id = p_otp_id
    and user_id = p_user_id
    and verified = true
    and consumed_at is null
    and reset_token_hash = p_token_hash
    and reset_token_expires_at > now()
  for update;

  if v_otp_id is null then
    return false;
  end if;

  update public.users
  set password_hash = p_password_hash
  where id::text = p_user_id
    and status = 'active';
  get diagnostics v_updated = row_count;

  if v_updated <> 1 then
    return false;
  end if;

  delete from public.password_reset_otps where user_id = p_user_id;
  return true;
end;
$$;

revoke all on function public.record_password_reset_otp_failure(uuid, integer) from public;
revoke all on function public.complete_password_reset(uuid, text, text, text) from public;
grant execute on function public.record_password_reset_otp_failure(uuid, integer) to service_role;
grant execute on function public.complete_password_reset(uuid, text, text, text) to service_role;

-- Optional cleanup for a scheduled database job:
-- delete from public.password_reset_otps
-- where expires_at < now() - interval '1 day' or consumed_at < now() - interval '1 day';
